<?php

namespace Database\Seeders;

use App\Models\SuratKeluar;
use App\Models\Bagian;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SuratKeluarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get existing bagian and users
        $bagian = Bagian::where('status', 'Aktif')->get();
        $users = User::all();

        if ($bagian->isEmpty() || $users->isEmpty()) {
            $this->command->warn('No bagian or users found. Please run BagianSeeder and UserSeeder first.');
            return;
        }

        $sampleData = [
            // ANCHOR: Data untuk 7 Hari Terakhir (Current Week)
            [
                'nomor_surat' => 'SK/001/IX/2025',
                'tanggal_surat' => Carbon::now()->subDays(5),
                'tanggal_keluar' => Carbon::now()->subDays(4),
                'perihal' => 'Undangan Rapat Koordinasi Bulanan',
                'ringkasan_isi' => 'Undangan untuk menghadiri rapat koordinasi bulanan yang akan membahas program kerja dan evaluasi kinerja.',
                'tujuan' => 'Kepala Bagian Kepegawaian',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Surat undangan rutin bulanan',
            ],
            [
                'nomor_surat' => 'SK/002/IX/2025',
                'tanggal_surat' => Carbon::now()->subDays(3),
                'tanggal_keluar' => Carbon::now()->subDays(2),
                'perihal' => 'Pemberitahuan Perubahan Jadwal Kerja',
                'ringkasan_isi' => 'Pemberitahuan mengenai perubahan jadwal kerja mulai bulan depan dengan sistem shift.',
                'tujuan' => 'Semua Pegawai',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Perubahan kebijakan penting',
            ],
            [
                'nomor_surat' => 'SK/003/IX/2025',
                'tanggal_surat' => Carbon::now()->subDay(),
                'tanggal_keluar' => Carbon::now()->subHours(12),
                'perihal' => 'Surat Keputusan Pengangkatan Pegawai',
                'ringkasan_isi' => 'Surat keputusan pengangkatan pegawai baru berdasarkan hasil seleksi dan wawancara.',
                'tujuan' => 'HRD dan Bagian Kepegawaian',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Informasi personal pegawai',
            ],

            // ANCHOR: Data untuk 30 Hari Terakhir (Current Month)
            [
                'nomor_surat' => 'SK/004/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(12),
                'tanggal_keluar' => Carbon::now()->subDays(11),
                'perihal' => 'Laporan Keuangan Triwulan III',
                'ringkasan_isi' => 'Laporan keuangan triwulan III tahun 2025 yang mencakup realisasi anggaran dan analisis kinerja keuangan.',
                'tujuan' => 'Kepala Bagian Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Laporan rutin triwulanan',
            ],
            [
                'nomor_surat' => 'SK/005/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(18),
                'tanggal_keluar' => Carbon::now()->subDays(17),
                'perihal' => 'Permohonan Izin Cuti Tahunan',
                'ringkasan_isi' => 'Permohonan izin cuti tahunan untuk keperluan keluarga dan kesehatan.',
                'tujuan' => 'Atasan Langsung',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Permohonan cuti rutin',
            ],
            [
                'nomor_surat' => 'SK/006/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(22),
                'tanggal_keluar' => Carbon::now()->subDays(21),
                'perihal' => 'Pemberitahuan Audit Internal',
                'ringkasan_isi' => 'Pemberitahuan akan dilaksanakannya audit internal untuk evaluasi sistem dan prosedur kerja.',
                'tujuan' => 'Semua Bagian',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Audit rutin tahunan',
            ],

            // ANCHOR: Data untuk 90 Hari Terakhir (Last 3 Months)
            [
                'nomor_surat' => 'SK/007/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(40),
                'tanggal_keluar' => Carbon::now()->subDays(39),
                'perihal' => 'Surat Tugas Dinas Luar',
                'ringkasan_isi' => 'Surat tugas untuk melaksanakan dinas luar dalam rangka koordinasi dengan instansi terkait.',
                'tujuan' => 'Petugas yang Ditugaskan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Tugas koordinasi eksternal',
            ],
            [
                'nomor_surat' => 'SK/008/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(55),
                'tanggal_keluar' => Carbon::now()->subDays(54),
                'perihal' => 'Evaluasi Kinerja Pegawai',
                'ringkasan_isi' => 'Dokumen evaluasi kinerja pegawai untuk periode semester ganjil tahun 2025.',
                'tujuan' => 'Bagian SDM',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Data evaluasi personal',
            ],
            [
                'nomor_surat' => 'SK/009/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(70),
                'tanggal_keluar' => Carbon::now()->subDays(69),
                'perihal' => 'Surat Tugas Pelatihan SDM',
                'ringkasan_isi' => 'Surat tugas untuk mengikuti pelatihan peningkatan kompetensi SDM di lembaga pelatihan terakreditasi.',
                'tujuan' => 'Bagian SDM',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Pengembangan kompetensi',
            ],

            // ANCHOR: Data untuk Tahun 2024
            [
                'nomor_surat' => 'SK/010/XII/2024',
                'tanggal_surat' => Carbon::create(2024, 12, 10),
                'tanggal_keluar' => Carbon::create(2024, 12, 11),
                'perihal' => 'Laporan Akhir Tahun 2024',
                'ringkasan_isi' => 'Laporan akhir tahun yang mencakup pencapaian target dan evaluasi kinerja instansi sepanjang tahun 2024.',
                'tujuan' => 'Kepala Instansi',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Laporan tahunan 2024',
            ],
            [
                'nomor_surat' => 'SK/011/XII/2024',
                'tanggal_surat' => Carbon::create(2024, 11, 25),
                'tanggal_keluar' => Carbon::create(2024, 11, 26),
                'perihal' => 'Rencana Kerja Tahun 2025',
                'ringkasan_isi' => 'Dokumen rencana kerja tahun 2025 yang mencakup program, target, dan strategi pencapaian.',
                'tujuan' => 'Badan Perencanaan Pembangunan Nasional',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Perencanaan tahun 2025',
            ],
            [
                'nomor_surat' => 'SK/012/XII/2024',
                'tanggal_surat' => Carbon::create(2024, 10, 15),
                'tanggal_keluar' => Carbon::create(2024, 10, 16),
                'perihal' => 'Surat Tugas Monitoring Program',
                'ringkasan_isi' => 'Surat tugas untuk melaksanakan monitoring program kerja tahun 2024 di berbagai wilayah.',
                'tujuan' => 'Tim Monitoring',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Monitoring program 2024',
            ],

            // ANCHOR: Data untuk Tahun 2023
            [
                'nomor_surat' => 'SK/013/XII/2023',
                'tanggal_surat' => Carbon::create(2023, 12, 18),
                'tanggal_keluar' => Carbon::create(2023, 12, 19),
                'perihal' => 'Evaluasi Akhir Tahun 2023',
                'ringkasan_isi' => 'Dokumen evaluasi akhir tahun 2023 yang mencakup analisis pencapaian dan tantangan yang dihadapi.',
                'tujuan' => 'Kepala Instansi',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Evaluasi tahunan 2023',
            ],
            [
                'nomor_surat' => 'SK/014/XI/2023',
                'tanggal_surat' => Carbon::create(2023, 11, 20),
                'tanggal_keluar' => Carbon::create(2023, 11, 21),
                'perihal' => 'Sosialisasi Kebijakan Baru 2024',
                'ringkasan_isi' => 'Materi sosialisasi kebijakan baru yang akan berlaku mulai tahun 2024.',
                'tujuan' => 'Semua Bagian',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Sosialisasi kebijakan',
            ],

            // ANCHOR: Data Tambahan untuk Variasi Lebih Banyak
            [
                'nomor_surat' => 'SK/015/IX/2025',
                'tanggal_surat' => Carbon::now()->subDays(2),
                'tanggal_keluar' => Carbon::now()->subDays(1),
                'perihal' => 'Laporan Bulanan September 2025',
                'ringkasan_isi' => 'Laporan kegiatan dan pencapaian program kerja bulan September 2025 untuk evaluasi kinerja bulanan.',
                'tujuan' => 'Kementerian Dalam Negeri',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Laporan bulanan',
            ],
            [
                'nomor_surat' => 'SK/016/IX/2025',
                'tanggal_surat' => Carbon::now()->subHours(12),
                'tanggal_keluar' => Carbon::now()->subHours(8),
                'perihal' => 'Permohonan Bantuan Teknis',
                'ringkasan_isi' => 'Permohonan bantuan teknis untuk implementasi sistem informasi manajemen yang baru.',
                'tujuan' => 'Dinas Komunikasi dan Informatika',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Permohonan bantuan',
            ],
            [
                'nomor_surat' => 'SK/017/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(9),
                'tanggal_keluar' => Carbon::now()->subDays(8),
                'perihal' => 'Undangan Rapat Koordinasi',
                'ringkasan_isi' => 'Undangan rapat koordinasi antar instansi untuk membahas program kerja bersama.',
                'tujuan' => 'Sekretariat Daerah',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Rapat koordinasi',
            ],
            [
                'nomor_surat' => 'SK/018/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(11),
                'tanggal_keluar' => Carbon::now()->subDays(10),
                'perihal' => 'Laporan Hasil Survei',
                'ringkasan_isi' => 'Laporan hasil survei kepuasan masyarakat terhadap pelayanan publik yang diselenggarakan.',
                'tujuan' => 'Badan Pusat Statistik',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Laporan survei',
            ],
            [
                'nomor_surat' => 'SK/019/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(15),
                'tanggal_keluar' => Carbon::now()->subDays(14),
                'perihal' => 'Koordinasi Program Unggulan',
                'ringkasan_isi' => 'Koordinasi pelaksanaan program unggulan instansi dengan stakeholder terkait.',
                'tujuan' => 'Kementerian Perencanaan',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Koordinasi program',
            ],
            [
                'nomor_surat' => 'SK/020/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(17),
                'tanggal_keluar' => Carbon::now()->subDays(16),
                'perihal' => 'Laporan Audit Internal',
                'ringkasan_isi' => 'Laporan hasil audit internal untuk memastikan kepatuhan terhadap prosedur dan regulasi.',
                'tujuan' => 'Inspektorat Jenderal',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Audit internal',
            ],
            [
                'nomor_surat' => 'SK/021/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(22),
                'tanggal_keluar' => Carbon::now()->subDays(21),
                'perihal' => 'Permohonan Sertifikasi ISO',
                'ringkasan_isi' => 'Permohonan sertifikasi ISO 9001:2015 untuk sistem manajemen mutu instansi.',
                'tujuan' => 'Badan Sertifikasi ISO',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Sertifikasi ISO',
            ],
            [
                'nomor_surat' => 'SK/022/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(25),
                'tanggal_keluar' => Carbon::now()->subDays(24),
                'perihal' => 'Laporan Kerjasama Riset',
                'ringkasan_isi' => 'Laporan hasil kerjasama riset dan pengembangan teknologi dengan lembaga penelitian.',
                'tujuan' => 'LIPI',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Kerjasama riset',
            ],
            [
                'nomor_surat' => 'SK/023/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(28),
                'tanggal_keluar' => Carbon::now()->subDays(27),
                'perihal' => 'Laporan Pelatihan SDM',
                'ringkasan_isi' => 'Laporan pelaksanaan program peningkatan kapasitas sumber daya manusia.',
                'tujuan' => 'LAN',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Pelatihan SDM',
            ],
            [
                'nomor_surat' => 'SK/024/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(36),
                'tanggal_keluar' => Carbon::now()->subDays(35),
                'perihal' => 'Laporan Implementasi E-Government',
                'ringkasan_isi' => 'Laporan progress implementasi sistem e-government untuk digitalisasi layanan publik.',
                'tujuan' => 'Kementerian Kominfo',
                'sifat_surat' => 'Segera',
                'keterangan' => 'E-government',
            ],
            [
                'nomor_surat' => 'SK/025/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(43),
                'tanggal_keluar' => Carbon::now()->subDays(42),
                'perihal' => 'Laporan Audit Keamanan Sistem',
                'ringkasan_isi' => 'Laporan hasil audit keamanan sistem informasi untuk memastikan perlindungan data.',
                'tujuan' => 'BSSN',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Audit keamanan',
            ],
            [
                'nomor_surat' => 'SK/026/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(49),
                'tanggal_keluar' => Carbon::now()->subDays(48),
                'perihal' => 'Laporan Penilaian Kinerja',
                'ringkasan_isi' => 'Laporan hasil penilaian kinerja organisasi berdasarkan indikator kinerja utama.',
                'tujuan' => 'KemenPANRB',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Penilaian kinerja',
            ],
            [
                'nomor_surat' => 'SK/027/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(53),
                'tanggal_keluar' => Carbon::now()->subDays(52),
                'perihal' => 'Laporan Pengadaan Barang/Jasa',
                'ringkasan_isi' => 'Laporan realisasi pengadaan barang dan jasa untuk mendukung operasional instansi.',
                'tujuan' => 'LKPP',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Pengadaan barang/jasa',
            ],
            [
                'nomor_surat' => 'SK/028/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(59),
                'tanggal_keluar' => Carbon::now()->subDays(58),
                'perihal' => 'Laporan Standar Operasional',
                'ringkasan_isi' => 'Laporan implementasi standar operasional prosedur untuk meningkatkan efektivitas kerja.',
                'tujuan' => 'Badan Standarisasi Nasional',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Standar operasional',
            ],
            [
                'nomor_surat' => 'SK/029/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(66),
                'tanggal_keluar' => Carbon::now()->subDays(65),
                'perihal' => 'Laporan Monitoring Kinerja',
                'ringkasan_isi' => 'Laporan monitoring dan evaluasi kinerja instansi untuk memastikan pencapaian target.',
                'tujuan' => 'Inspektorat Jenderal',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Monitoring kinerja',
            ],
            [
                'nomor_surat' => 'SK/030/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(73),
                'tanggal_keluar' => Carbon::now()->subDays(72),
                'perihal' => 'Laporan Sosialisasi Regulasi',
                'ringkasan_isi' => 'Laporan sosialisasi perubahan regulasi kepada seluruh stakeholder terkait.',
                'tujuan' => 'Kementerian Hukum dan HAM',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Sosialisasi regulasi',
            ],
            [
                'nomor_surat' => 'SK/031/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(79),
                'tanggal_keluar' => Carbon::now()->subDays(78),
                'perihal' => 'Laporan Sistem Akuntansi',
                'ringkasan_isi' => 'Laporan implementasi sistem akuntansi berbasis akrual untuk transparansi keuangan.',
                'tujuan' => 'Kementerian Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Sistem akuntansi',
            ],
            [
                'nomor_surat' => 'SK/032/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(86),
                'tanggal_keluar' => Carbon::now()->subDays(85),
                'perihal' => 'Laporan Program Pemberdayaan',
                'ringkasan_isi' => 'Laporan pelaksanaan program pemberdayaan masyarakat untuk meningkatkan partisipasi publik.',
                'tujuan' => 'Kementerian Desa',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Pemberdayaan masyarakat',
            ],
            [
                'nomor_surat' => 'SK/033/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(89),
                'tanggal_keluar' => Carbon::now()->subDays(88),
                'perihal' => 'Laporan Audit Kepatuhan',
                'ringkasan_isi' => 'Laporan audit kepatuhan internal untuk memastikan ketaatan terhadap regulasi.',
                'tujuan' => 'Internal Audit',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Audit kepatuhan',
            ],
            [
                'nomor_surat' => 'SK/034/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(96),
                'tanggal_keluar' => Carbon::now()->subDays(95),
                'perihal' => 'Laporan Smart Office',
                'ringkasan_isi' => 'Laporan implementasi konsep smart office untuk meningkatkan efisiensi kerja.',
                'tujuan' => 'Kementerian PUPR',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Smart office',
            ],
            [
                'nomor_surat' => 'SK/035/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(103),
                'tanggal_keluar' => Carbon::now()->subDays(102),
                'perihal' => 'Laporan Pengelolaan Aset',
                'ringkasan_isi' => 'Laporan pengelolaan aset negara untuk optimalisasi pemanfaatan dan pemeliharaan.',
                'tujuan' => 'Kementerian BUMN',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Pengelolaan aset',
            ],
            [
                'nomor_surat' => 'SK/036/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(109),
                'tanggal_keluar' => Carbon::now()->subDays(108),
                'perihal' => 'Laporan Sertifikasi Kompetensi',
                'ringkasan_isi' => 'Laporan program sertifikasi kompetensi profesi untuk peningkatan kualitas SDM.',
                'tujuan' => 'BNSP',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Sertifikasi kompetensi',
            ],
            [
                'nomor_surat' => 'SK/037/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(116),
                'tanggal_keluar' => Carbon::now()->subDays(115),
                'perihal' => 'Laporan Manajemen Risiko',
                'ringkasan_isi' => 'Laporan implementasi sistem manajemen risiko untuk identifikasi dan pengelolaan risiko.',
                'tujuan' => 'Kementerian Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen risiko',
            ],
            [
                'nomor_surat' => 'SK/038/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(121),
                'tanggal_keluar' => Carbon::now()->subDays(120),
                'perihal' => 'Laporan Program Inovasi',
                'ringkasan_isi' => 'Laporan pelaksanaan program inovasi untuk solusi kreatif dalam pelayanan publik.',
                'tujuan' => 'Kemenristekdikti',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Program inovasi',
            ],
            [
                'nomor_surat' => 'SK/039/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(126),
                'tanggal_keluar' => Carbon::now()->subDays(125),
                'perihal' => 'Laporan Audit Sistem Informasi',
                'ringkasan_isi' => 'Laporan audit sistem informasi manajemen untuk keamanan dan efektivitas teknologi.',
                'tujuan' => 'Badan Audit IT',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Audit sistem informasi',
            ],
            [
                'nomor_surat' => 'SK/040/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(131),
                'tanggal_keluar' => Carbon::now()->subDays(130),
                'perihal' => 'Laporan Good Corporate Governance',
                'ringkasan_isi' => 'Laporan implementasi good corporate governance untuk transparansi dan akuntabilitas.',
                'tujuan' => 'Komite Nasional GCG',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Good corporate governance',
            ],
            [
                'nomor_surat' => 'SK/041/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(136),
                'tanggal_keluar' => Carbon::now()->subDays(135),
                'perihal' => 'Laporan Program CSR',
                'ringkasan_isi' => 'Laporan pelaksanaan program corporate social responsibility untuk kontribusi sosial.',
                'tujuan' => 'Kementerian Sosial',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Program CSR',
            ],
            [
                'nomor_surat' => 'SK/042/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(141),
                'tanggal_keluar' => Carbon::now()->subDays(140),
                'perihal' => 'Laporan Manajemen Lingkungan',
                'ringkasan_isi' => 'Laporan implementasi sistem manajemen lingkungan untuk operasional ramah lingkungan.',
                'tujuan' => 'Kementerian LHK',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen lingkungan',
            ],
            [
                'nomor_surat' => 'SK/043/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(146),
                'tanggal_keluar' => Carbon::now()->subDays(145),
                'perihal' => 'Laporan Program K3',
                'ringkasan_isi' => 'Laporan pelaksanaan program keselamatan dan kesehatan kerja untuk perlindungan karyawan.',
                'tujuan' => 'Kementerian Ketenagakerjaan',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Program K3',
            ],
            [
                'nomor_surat' => 'SK/044/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(151),
                'tanggal_keluar' => Carbon::now()->subDays(150),
                'perihal' => 'Laporan Manajemen Mutu',
                'ringkasan_isi' => 'Laporan implementasi sistem manajemen mutu untuk kualitas produk dan layanan.',
                'tujuan' => 'Badan Standarisasi Nasional',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen mutu',
            ],
            [
                'nomor_surat' => 'SK/045/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(156),
                'tanggal_keluar' => Carbon::now()->subDays(155),
                'perihal' => 'Laporan Pengembangan UKM',
                'ringkasan_isi' => 'Laporan pelaksanaan program pengembangan usaha kecil dan menengah.',
                'tujuan' => 'Kementerian Koperasi dan UKM',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Pengembangan UKM',
            ],
            [
                'nomor_surat' => 'SK/046/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(161),
                'tanggal_keluar' => Carbon::now()->subDays(160),
                'perihal' => 'Laporan Manajemen Energi',
                'ringkasan_isi' => 'Laporan implementasi sistem manajemen energi untuk efisiensi penggunaan energi.',
                'tujuan' => 'Kementerian ESDM',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Manajemen energi',
            ],
            [
                'nomor_surat' => 'SK/047/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(166),
                'tanggal_keluar' => Carbon::now()->subDays(165),
                'perihal' => 'Laporan Program Pariwisata',
                'ringkasan_isi' => 'Laporan pelaksanaan program pengembangan pariwisata untuk pertumbuhan ekonomi.',
                'tujuan' => 'Kementerian Pariwisata',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Program pariwisata',
            ],
            [
                'nomor_surat' => 'SK/048/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(171),
                'tanggal_keluar' => Carbon::now()->subDays(170),
                'perihal' => 'Laporan Manajemen Pengetahuan',
                'ringkasan_isi' => 'Laporan implementasi sistem manajemen pengetahuan untuk pembelajaran organisasi.',
                'tujuan' => 'Kementerian Pendidikan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen pengetahuan',
            ],
            [
                'nomor_surat' => 'SK/049/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(176),
                'tanggal_keluar' => Carbon::now()->subDays(175),
                'perihal' => 'Laporan Program Digitalisasi',
                'ringkasan_isi' => 'Laporan pelaksanaan program digitalisasi untuk efisiensi layanan publik.',
                'tujuan' => 'Kementerian Kominfo',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Program digitalisasi',
            ],
            [
                'nomor_surat' => 'SK/050/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(181),
                'tanggal_keluar' => Carbon::now()->subDays(180),
                'perihal' => 'Laporan Manajemen Proyek',
                'ringkasan_isi' => 'Laporan implementasi sistem manajemen proyek untuk efektivitas program kerja.',
                'tujuan' => 'Kementerian PPN',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen proyek',
            ],

            // ANCHOR: Data untuk Tahun 2022
            [
                'nomor_surat' => 'SK/051/XII/2022',
                'tanggal_surat' => Carbon::create(2022, 12, 20),
                'tanggal_keluar' => Carbon::create(2022, 12, 21),
                'perihal' => 'Laporan Akhir Tahun 2022',
                'ringkasan_isi' => 'Laporan akhir tahun yang mencakup pencapaian target dan evaluasi kinerja instansi sepanjang tahun 2022.',
                'tujuan' => 'Kementerian Pendayagunaan Aparatur Negara',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Laporan tahunan 2022',
            ],
            [
                'nomor_surat' => 'SK/052/XI/2022',
                'tanggal_surat' => Carbon::create(2022, 11, 25),
                'tanggal_keluar' => Carbon::create(2022, 11, 26),
                'perihal' => 'Rencana Kerja Tahun 2023',
                'ringkasan_isi' => 'Dokumen rencana kerja tahun 2023 yang mencakup program, target, dan strategi pencapaian.',
                'tujuan' => 'Badan Perencanaan Pembangunan Nasional',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Perencanaan tahun 2023',
            ],
            [
                'nomor_surat' => 'SK/053/X/2022',
                'tanggal_surat' => Carbon::create(2022, 10, 15),
                'tanggal_keluar' => Carbon::create(2022, 10, 16),
                'perihal' => 'Laporan Audit Kinerja Triwulan III',
                'ringkasan_isi' => 'Laporan hasil audit kinerja triwulan III tahun 2022 dengan rekomendasi perbaikan.',
                'tujuan' => 'Badan Pemeriksa Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Audit triwulan III 2022',
            ],
            [
                'nomor_surat' => 'SK/054/IX/2022',
                'tanggal_surat' => Carbon::create(2022, 9, 10),
                'tanggal_keluar' => Carbon::create(2022, 9, 11),
                'perihal' => 'Laporan Implementasi Sistem Akuntansi',
                'ringkasan_isi' => 'Laporan implementasi sistem akuntansi berbasis akrual untuk transparansi keuangan.',
                'tujuan' => 'Kementerian Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Sistem akuntansi akrual',
            ],
            [
                'nomor_surat' => 'SK/055/VIII/2022',
                'tanggal_surat' => Carbon::create(2022, 8, 20),
                'tanggal_keluar' => Carbon::create(2022, 8, 21),
                'perihal' => 'Laporan Program Reformasi Birokrasi',
                'ringkasan_isi' => 'Laporan pelaksanaan program reformasi birokrasi untuk peningkatan kualitas pelayanan.',
                'tujuan' => 'Kementerian PANRB',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Reformasi birokrasi',
            ],
        ];

        foreach ($sampleData as $data) {
            // Random bagian dan user
            $randomBagian = $bagian->random();
            $randomUser = $users->random();

            SuratKeluar::create([
                'nomor_surat' => $data['nomor_surat'],
                'tanggal_surat' => $data['tanggal_surat'],
                'tanggal_keluar' => $data['tanggal_keluar'],
                'perihal' => $data['perihal'],
                'ringkasan_isi' => $data['ringkasan_isi'],
                'tujuan' => $data['tujuan'],
                'sifat_surat' => $data['sifat_surat'],
                'keterangan' => $data['keterangan'],
                'pengirim_bagian_id' => $randomBagian->id,
                'user_id' => $randomUser->id,
                'created_by' => $randomUser->id,
                'updated_by' => $randomUser->id,
            ]);
        }

        $this->command->info('SuratKeluarSeeder completed successfully!');
    }
}
