<?php

namespace Database\Seeders;

use App\Models\SuratMasuk;
use App\Models\Bagian;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SuratMasukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get existing bagian and users
        $bagian = Bagian::where('status', 'Aktif')->get();
        $users = User::all();

        if ($bagian->isEmpty() || $users->isEmpty()) {
            $this->command->warn('No bagian or users found. Please run BagianSeeder and UserSeeder first.');
            return;
        }

        $sampleData = [
            // ANCHOR: Data untuk 7 Hari Terakhir (Current Week)
            [
                'nomor_surat' => 'SM/001/IX/2025',
                'tanggal_surat' => Carbon::now()->subDays(6),
                'tanggal_terima' => Carbon::now()->subDays(5),
                'perihal' => 'Undangan Rapat Koordinasi Antar Instansi',
                'ringkasan_isi' => 'Undangan untuk menghadiri rapat koordinasi antar instansi pemerintah dalam rangka sinkronisasi program kerja.',
                'pengirim' => 'Kementerian Dalam Negeri',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Undangan rapat penting',
            ],
            [
                'nomor_surat' => 'SM/002/IX/2025',
                'tanggal_surat' => Carbon::now()->subDays(4),
                'tanggal_terima' => Carbon::now()->subDays(3),
                'perihal' => 'Permohonan Data dan Informasi',
                'ringkasan_isi' => 'Permohonan data dan informasi terkait kinerja instansi untuk keperluan evaluasi dan pelaporan.',
                'pengirim' => 'Badan Pusat Statistik',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Permohonan data rutin',
            ],
            [
                'nomor_surat' => 'SM/003/IX/2025',
                'tanggal_surat' => Carbon::now()->subDays(2),
                'tanggal_terima' => Carbon::now()->subDay(),
                'perihal' => 'Pemberitahuan Audit Eksternal',
                'ringkasan_isi' => 'Pemberitahuan akan dilaksanakannya audit eksternal oleh Badan Pemeriksa Keuangan untuk evaluasi keuangan instansi.',
                'pengirim' => 'Badan Pemeriksa Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Audit eksternal rutin',
            ],
            [
                'nomor_surat' => 'SM/004/IX/2025',
                'tanggal_surat' => Carbon::now()->subHours(12),
                'tanggal_terima' => Carbon::now()->subHours(6),
                'perihal' => 'Surat Keputusan Mutasi Pegawai',
                'ringkasan_isi' => 'Surat keputusan mutasi pegawai antar instansi berdasarkan kebutuhan dan kompetensi.',
                'pengirim' => 'Badan Kepegawaian Negara',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Informasi personal pegawai',
            ],

            // ANCHOR: Data untuk 30 Hari Terakhir (Current Month)
            [
                'nomor_surat' => 'SM/005/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(15),
                'tanggal_terima' => Carbon::now()->subDays(14),
                'perihal' => 'Laporan Keuangan Bulanan',
                'ringkasan_isi' => 'Laporan keuangan bulanan yang mencakup realisasi anggaran dan analisis kinerja keuangan instansi.',
                'pengirim' => 'Kementerian Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Laporan rutin bulanan',
            ],
            [
                'nomor_surat' => 'SM/006/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(20),
                'tanggal_terima' => Carbon::now()->subDays(19),
                'perihal' => 'Undangan Pelatihan dan Pengembangan',
                'ringkasan_isi' => 'Undangan untuk mengikuti pelatihan dan pengembangan kompetensi pegawai dalam rangka peningkatan kualitas SDM.',
                'pengirim' => 'Lembaga Administrasi Negara',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Pelatihan pengembangan SDM',
            ],
            [
                'nomor_surat' => 'SM/007/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(25),
                'tanggal_terima' => Carbon::now()->subDays(24),
                'perihal' => 'Pemberitahuan Perubahan Kebijakan',
                'ringkasan_isi' => 'Pemberitahuan mengenai perubahan kebijakan pemerintah yang berdampak pada operasional instansi.',
                'pengirim' => 'Sekretariat Kabinet',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Perubahan kebijakan penting',
            ],

            // ANCHOR: Data untuk 90 Hari Terakhir (Last 3 Months)
            [
                'nomor_surat' => 'SM/008/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(45),
                'tanggal_terima' => Carbon::now()->subDays(44),
                'perihal' => 'Surat Tugas Monitoring dan Evaluasi',
                'ringkasan_isi' => 'Surat tugas untuk melaksanakan monitoring dan evaluasi program kerja instansi dalam rangka peningkatan kinerja.',
                'pengirim' => 'Inspektorat Jenderal',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Monitoring dan evaluasi rutin',
            ],
            [
                'nomor_surat' => 'SM/009/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(60),
                'tanggal_terima' => Carbon::now()->subDays(59),
                'perihal' => 'Permohonan Kerjasama Teknis',
                'ringkasan_isi' => 'Permohonan kerjasama teknis dalam bidang teknologi informasi untuk mendukung digitalisasi layanan publik.',
                'pengirim' => 'Kementerian Komunikasi dan Informatika',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Kerjasama teknis IT',
            ],
            [
                'nomor_surat' => 'SM/010/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(75),
                'tanggal_terima' => Carbon::now()->subDays(74),
                'perihal' => 'Evaluasi Kinerja Instansi',
                'ringkasan_isi' => 'Dokumen evaluasi kinerja instansi untuk periode semester ganjil tahun 2025 yang mencakup berbagai aspek kinerja.',
                'pengirim' => 'Kementerian Pendayagunaan Aparatur Negara',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Evaluasi kinerja instansi',
            ],

            // ANCHOR: Data untuk Tahun 2024
            [
                'nomor_surat' => 'SM/011/XII/2024',
                'tanggal_surat' => Carbon::create(2024, 12, 15),
                'tanggal_terima' => Carbon::create(2024, 12, 16),
                'perihal' => 'Laporan Akhir Tahun 2024',
                'ringkasan_isi' => 'Laporan akhir tahun yang mencakup pencapaian target dan evaluasi kinerja instansi sepanjang tahun 2024.',
                'pengirim' => 'Kementerian Pendayagunaan Aparatur Negara',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Laporan tahunan 2024',
            ],
            [
                'nomor_surat' => 'SM/012/XII/2024',
                'tanggal_surat' => Carbon::create(2024, 11, 20),
                'tanggal_terima' => Carbon::create(2024, 11, 21),
                'perihal' => 'Rencana Kerja Tahun 2025',
                'ringkasan_isi' => 'Dokumen rencana kerja tahun 2025 yang mencakup program, target, dan strategi pencapaian.',
                'pengirim' => 'Badan Perencanaan Pembangunan Nasional',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Perencanaan tahun 2025',
            ],
            [
                'nomor_surat' => 'SM/013/XII/2024',
                'tanggal_surat' => Carbon::create(2024, 10, 10),
                'tanggal_terima' => Carbon::create(2024, 10, 11),
                'perihal' => 'Audit Kinerja Triwulan III 2024',
                'ringkasan_isi' => 'Hasil audit kinerja triwulan III tahun 2024 dengan rekomendasi perbaikan untuk triwulan IV.',
                'pengirim' => 'Badan Pemeriksa Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Audit triwulan III 2024',
            ],

            // ANCHOR: Data untuk Tahun 2023
            [
                'nomor_surat' => 'SM/014/XII/2023',
                'tanggal_surat' => Carbon::create(2023, 12, 20),
                'tanggal_terima' => Carbon::create(2023, 12, 21),
                'perihal' => 'Evaluasi Akhir Tahun 2023',
                'ringkasan_isi' => 'Dokumen evaluasi akhir tahun 2023 yang mencakup analisis pencapaian dan tantangan yang dihadapi.',
                'pengirim' => 'Kementerian Dalam Negeri',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Evaluasi tahunan 2023',
            ],
            [
                'nomor_surat' => 'SM/015/XI/2023',
                'tanggal_surat' => Carbon::create(2023, 11, 15),
                'tanggal_terima' => Carbon::create(2023, 11, 16),
                'perihal' => 'Sosialisasi Kebijakan Baru 2024',
                'ringkasan_isi' => 'Materi sosialisasi kebijakan baru yang akan berlaku mulai tahun 2024.',
                'pengirim' => 'Sekretariat Kabinet',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Sosialisasi kebijakan',
            ],

            // ANCHOR: Data Tambahan untuk Variasi Lebih Banyak
            [
                'nomor_surat' => 'SM/016/IX/2025',
                'tanggal_surat' => Carbon::now()->subDays(1),
                'tanggal_terima' => Carbon::now()->subHours(18),
                'perihal' => 'Permohonan Bantuan Teknis Sistem',
                'ringkasan_isi' => 'Permohonan bantuan teknis untuk perbaikan sistem informasi manajemen yang mengalami gangguan.',
                'pengirim' => 'Dinas Komunikasi dan Informatika',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Permohonan bantuan teknis',
            ],
            [
                'nomor_surat' => 'SM/017/IX/2025',
                'tanggal_surat' => Carbon::now()->subHours(6),
                'tanggal_terima' => Carbon::now()->subHours(4),
                'perihal' => 'Undangan Workshop Digitalisasi',
                'ringkasan_isi' => 'Undangan workshop digitalisasi layanan publik untuk meningkatkan efisiensi dan transparansi.',
                'pengirim' => 'Kementerian PANRB',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Workshop digitalisasi',
            ],
            [
                'nomor_surat' => 'SM/018/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(8),
                'tanggal_terima' => Carbon::now()->subDays(7),
                'perihal' => 'Survei Kepuasan Masyarakat',
                'ringkasan_isi' => 'Survei kepuasan masyarakat terhadap kualitas pelayanan publik yang diselenggarakan instansi.',
                'pengirim' => 'Badan Pusat Statistik',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Survei kepuasan masyarakat',
            ],
            [
                'nomor_surat' => 'SM/019/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(10),
                'tanggal_terima' => Carbon::now()->subDays(9),
                'perihal' => 'Koordinasi Penanganan Bencana',
                'ringkasan_isi' => 'Koordinasi penanganan bencana alam dan darurat untuk memastikan kesiapsiagaan instansi.',
                'pengirim' => 'BNPB',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Koordinasi bencana',
            ],
            [
                'nomor_surat' => 'SM/020/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(14),
                'tanggal_terima' => Carbon::now()->subDays(13),
                'perihal' => 'Evaluasi Program Unggulan',
                'ringkasan_isi' => 'Evaluasi program unggulan instansi untuk mengukur dampak dan efektivitas implementasi.',
                'pengirim' => 'Kementerian Perencanaan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Evaluasi program',
            ],
            [
                'nomor_surat' => 'SM/021/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(16),
                'tanggal_terima' => Carbon::now()->subDays(15),
                'perihal' => 'Sertifikasi ISO 9001:2015',
                'ringkasan_isi' => 'Persiapan dan pelaksanaan audit sertifikasi ISO 9001:2015 untuk sistem manajemen mutu.',
                'pengirim' => 'Badan Sertifikasi ISO',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Sertifikasi ISO',
            ],
            [
                'nomor_surat' => 'SM/022/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(21),
                'tanggal_terima' => Carbon::now()->subDays(20),
                'perihal' => 'Kerjasama Riset dan Pengembangan',
                'ringkasan_isi' => 'Penawaran kerjasama riset dan pengembangan teknologi untuk mendukung inovasi instansi.',
                'pengirim' => 'LIPI',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Kerjasama riset',
            ],
            [
                'nomor_surat' => 'SM/023/VIII/2025',
                'tanggal_surat' => Carbon::now()->subDays(24),
                'tanggal_terima' => Carbon::now()->subDays(23),
                'perihal' => 'Peningkatan Kapasitas SDM',
                'ringkasan_isi' => 'Program peningkatan kapasitas sumber daya manusia melalui pelatihan dan pengembangan kompetensi.',
                'pengirim' => 'LAN',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Peningkatan kapasitas',
            ],
            [
                'nomor_surat' => 'SM/024/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(35),
                'tanggal_terima' => Carbon::now()->subDays(34),
                'perihal' => 'Implementasi E-Government',
                'ringkasan_isi' => 'Implementasi sistem e-government untuk meningkatkan kualitas layanan publik digital.',
                'pengirim' => 'Kominfo',
                'sifat_surat' => 'Segera',
                'keterangan' => 'E-government',
            ],
            [
                'nomor_surat' => 'SM/025/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(42),
                'tanggal_terima' => Carbon::now()->subDays(41),
                'perihal' => 'Audit Sistem Keamanan Informasi',
                'ringkasan_isi' => 'Audit sistem keamanan informasi untuk memastikan perlindungan data dan privasi.',
                'pengirim' => 'BSSN',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Audit keamanan',
            ],
            [
                'nomor_surat' => 'SM/026/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(48),
                'tanggal_terima' => Carbon::now()->subDays(47),
                'perihal' => 'Penilaian Kinerja Organisasi',
                'ringkasan_isi' => 'Penilaian kinerja organisasi berdasarkan indikator kinerja utama yang telah ditetapkan.',
                'pengirim' => 'KemenPANRB',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Penilaian kinerja',
            ],
            [
                'nomor_surat' => 'SM/027/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(52),
                'tanggal_terima' => Carbon::now()->subDays(51),
                'perihal' => 'Koordinasi Pengadaan Barang/Jasa',
                'ringkasan_isi' => 'Koordinasi pengadaan barang dan jasa untuk mendukung operasional instansi.',
                'pengirim' => 'LKPP',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Pengadaan barang/jasa',
            ],
            [
                'nomor_surat' => 'SM/028/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(58),
                'tanggal_terima' => Carbon::now()->subDays(57),
                'perihal' => 'Penyusunan Standar Operasional',
                'ringkasan_isi' => 'Penyusunan standar operasional prosedur untuk meningkatkan efektivitas kerja.',
                'pengirim' => 'Badan Standarisasi Nasional',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Standar operasional',
            ],
            [
                'nomor_surat' => 'SM/029/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(65),
                'tanggal_terima' => Carbon::now()->subDays(64),
                'perihal' => 'Monitoring dan Evaluasi Kinerja',
                'ringkasan_isi' => 'Monitoring dan evaluasi kinerja instansi untuk memastikan pencapaian target yang ditetapkan.',
                'pengirim' => 'Inspektorat Jenderal',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Monitoring kinerja',
            ],
            [
                'nomor_surat' => 'SM/030/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(72),
                'tanggal_terima' => Carbon::now()->subDays(71),
                'perihal' => 'Sosialisasi Perubahan Regulasi',
                'ringkasan_isi' => 'Sosialisasi perubahan regulasi yang berdampak pada operasional dan prosedur kerja instansi.',
                'pengirim' => 'Kementerian Hukum dan HAM',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Perubahan regulasi',
            ],
            [
                'nomor_surat' => 'SM/031/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(78),
                'tanggal_terima' => Carbon::now()->subDays(77),
                'perihal' => 'Implementasi Sistem Akuntansi',
                'ringkasan_isi' => 'Implementasi sistem akuntansi berbasis akrual untuk meningkatkan transparansi keuangan.',
                'pengirim' => 'Kementerian Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Sistem akuntansi',
            ],
            [
                'nomor_surat' => 'SM/032/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(85),
                'tanggal_terima' => Carbon::now()->subDays(84),
                'perihal' => 'Koordinasi Program Pemberdayaan',
                'ringkasan_isi' => 'Koordinasi program pemberdayaan masyarakat untuk meningkatkan partisipasi publik.',
                'pengirim' => 'Kementerian Desa',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Pemberdayaan masyarakat',
            ],
            [
                'nomor_surat' => 'SM/033/VII/2025',
                'tanggal_surat' => Carbon::now()->subDays(88),
                'tanggal_terima' => Carbon::now()->subDays(87),
                'perihal' => 'Audit Kepatuhan Internal',
                'ringkasan_isi' => 'Audit kepatuhan internal untuk memastikan ketaatan terhadap regulasi dan prosedur yang berlaku.',
                'pengirim' => 'Internal Audit',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Audit kepatuhan',
            ],
            [
                'nomor_surat' => 'SM/034/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(95),
                'tanggal_terima' => Carbon::now()->subDays(94),
                'perihal' => 'Implementasi Smart Office',
                'ringkasan_isi' => 'Implementasi konsep smart office untuk meningkatkan efisiensi dan produktivitas kerja.',
                'pengirim' => 'Kementerian PUPR',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Smart office',
            ],
            [
                'nomor_surat' => 'SM/035/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(102),
                'tanggal_terima' => Carbon::now()->subDays(101),
                'perihal' => 'Koordinasi Pengelolaan Aset',
                'ringkasan_isi' => 'Koordinasi pengelolaan aset negara untuk memastikan optimalisasi pemanfaatan dan pemeliharaan.',
                'pengirim' => 'Kementerian BUMN',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Pengelolaan aset',
            ],
            [
                'nomor_surat' => 'SM/036/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(108),
                'tanggal_terima' => Carbon::now()->subDays(107),
                'perihal' => 'Sertifikasi Kompetensi Profesi',
                'ringkasan_isi' => 'Program sertifikasi kompetensi profesi untuk meningkatkan kualitas sumber daya manusia.',
                'pengirim' => 'BNSP',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Sertifikasi kompetensi',
            ],
            [
                'nomor_surat' => 'SM/037/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(115),
                'tanggal_terima' => Carbon::now()->subDays(114),
                'perihal' => 'Implementasi Sistem Manajemen Risiko',
                'ringkasan_isi' => 'Implementasi sistem manajemen risiko untuk mengidentifikasi dan mengelola potensi risiko operasional.',
                'pengirim' => 'Kementerian Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen risiko',
            ],
            [
                'nomor_surat' => 'SM/038/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(120),
                'tanggal_terima' => Carbon::now()->subDays(119),
                'perihal' => 'Koordinasi Program Inovasi',
                'ringkasan_isi' => 'Koordinasi program inovasi untuk mendorong terciptanya solusi kreatif dalam pelayanan publik.',
                'pengirim' => 'Kemenristekdikti',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Program inovasi',
            ],
            [
                'nomor_surat' => 'SM/039/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(125),
                'tanggal_terima' => Carbon::now()->subDays(124),
                'perihal' => 'Audit Sistem Informasi Manajemen',
                'ringkasan_isi' => 'Audit sistem informasi manajemen untuk memastikan keamanan dan efektivitas penggunaan teknologi informasi.',
                'pengirim' => 'Badan Audit IT',
                'sifat_surat' => 'Rahasia',
                'keterangan' => 'Audit sistem informasi',
            ],
            [
                'nomor_surat' => 'SM/040/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(130),
                'tanggal_terima' => Carbon::now()->subDays(129),
                'perihal' => 'Implementasi Good Corporate Governance',
                'ringkasan_isi' => 'Implementasi prinsip-prinsip good corporate governance untuk meningkatkan transparansi dan akuntabilitas.',
                'pengirim' => 'Komite Nasional GCG',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Good corporate governance',
            ],
            [
                'nomor_surat' => 'SM/041/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(135),
                'tanggal_terima' => Carbon::now()->subDays(134),
                'perihal' => 'Koordinasi Program CSR',
                'ringkasan_isi' => 'Koordinasi program corporate social responsibility untuk meningkatkan kontribusi sosial instansi.',
                'pengirim' => 'Kementerian Sosial',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Program CSR',
            ],
            [
                'nomor_surat' => 'SM/042/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(140),
                'tanggal_terima' => Carbon::now()->subDays(139),
                'perihal' => 'Implementasi Sistem Manajemen Lingkungan',
                'ringkasan_isi' => 'Implementasi sistem manajemen lingkungan untuk memastikan operasional yang ramah lingkungan.',
                'pengirim' => 'Kementerian LHK',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen lingkungan',
            ],
            [
                'nomor_surat' => 'SM/043/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(145),
                'tanggal_terima' => Carbon::now()->subDays(144),
                'perihal' => 'Koordinasi Program K3',
                'ringkasan_isi' => 'Koordinasi program keselamatan dan kesehatan kerja untuk melindungi karyawan dari risiko kerja.',
                'pengirim' => 'Kementerian Ketenagakerjaan',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Program K3',
            ],
            [
                'nomor_surat' => 'SM/044/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(150),
                'tanggal_terima' => Carbon::now()->subDays(149),
                'perihal' => 'Implementasi Sistem Manajemen Mutu',
                'ringkasan_isi' => 'Implementasi sistem manajemen mutu untuk meningkatkan kualitas produk dan layanan instansi.',
                'pengirim' => 'Badan Standarisasi Nasional',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen mutu',
            ],
            [
                'nomor_surat' => 'SM/045/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(155),
                'tanggal_terima' => Carbon::now()->subDays(154),
                'perihal' => 'Koordinasi Program Pengembangan UKM',
                'ringkasan_isi' => 'Koordinasi program pengembangan usaha kecil dan menengah untuk mendorong pertumbuhan ekonomi.',
                'pengirim' => 'Kementerian Koperasi dan UKM',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Pengembangan UKM',
            ],
            [
                'nomor_surat' => 'SM/046/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(160),
                'tanggal_terima' => Carbon::now()->subDays(159),
                'perihal' => 'Implementasi Sistem Manajemen Energi',
                'ringkasan_isi' => 'Implementasi sistem manajemen energi untuk meningkatkan efisiensi penggunaan energi di instansi.',
                'pengirim' => 'Kementerian ESDM',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Manajemen energi',
            ],
            [
                'nomor_surat' => 'SM/047/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(165),
                'tanggal_terima' => Carbon::now()->subDays(164),
                'perihal' => 'Koordinasi Program Pariwisata',
                'ringkasan_isi' => 'Koordinasi program pengembangan pariwisata untuk mendorong pertumbuhan ekonomi daerah.',
                'pengirim' => 'Kementerian Pariwisata',
                'sifat_surat' => 'Biasa',
                'keterangan' => 'Program pariwisata',
            ],
            [
                'nomor_surat' => 'SM/048/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(170),
                'tanggal_terima' => Carbon::now()->subDays(169),
                'perihal' => 'Implementasi Sistem Manajemen Pengetahuan',
                'ringkasan_isi' => 'Implementasi sistem manajemen pengetahuan untuk meningkatkan pembelajaran organisasi.',
                'pengirim' => 'Kementerian Pendidikan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen pengetahuan',
            ],
            [
                'nomor_surat' => 'SM/049/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(175),
                'tanggal_terima' => Carbon::now()->subDays(174),
                'perihal' => 'Koordinasi Program Digitalisasi',
                'ringkasan_isi' => 'Koordinasi program digitalisasi untuk meningkatkan efisiensi dan transparansi layanan publik.',
                'pengirim' => 'Kementerian Kominfo',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Program digitalisasi',
            ],
            [
                'nomor_surat' => 'SM/050/VI/2025',
                'tanggal_surat' => Carbon::now()->subDays(180),
                'tanggal_terima' => Carbon::now()->subDays(179),
                'perihal' => 'Implementasi Sistem Manajemen Proyek',
                'ringkasan_isi' => 'Implementasi sistem manajemen proyek untuk meningkatkan efektivitas pelaksanaan program kerja.',
                'pengirim' => 'Kementerian PPN',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Manajemen proyek',
            ],

            // ANCHOR: Data untuk Tahun 2022
            [
                'nomor_surat' => 'SM/051/XII/2022',
                'tanggal_surat' => Carbon::create(2022, 12, 15),
                'tanggal_terima' => Carbon::create(2022, 12, 16),
                'perihal' => 'Laporan Akhir Tahun 2022',
                'ringkasan_isi' => 'Laporan akhir tahun yang mencakup pencapaian target dan evaluasi kinerja instansi sepanjang tahun 2022.',
                'pengirim' => 'Kementerian Pendayagunaan Aparatur Negara',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Laporan tahunan 2022',
            ],
            [
                'nomor_surat' => 'SM/052/XI/2022',
                'tanggal_surat' => Carbon::create(2022, 11, 20),
                'tanggal_terima' => Carbon::create(2022, 11, 21),
                'perihal' => 'Rencana Kerja Tahun 2023',
                'ringkasan_isi' => 'Dokumen rencana kerja tahun 2023 yang mencakup program, target, dan strategi pencapaian.',
                'pengirim' => 'Badan Perencanaan Pembangunan Nasional',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Perencanaan tahun 2023',
            ],
            [
                'nomor_surat' => 'SM/053/X/2022',
                'tanggal_surat' => Carbon::create(2022, 10, 10),
                'tanggal_terima' => Carbon::create(2022, 10, 11),
                'perihal' => 'Audit Kinerja Triwulan III 2022',
                'ringkasan_isi' => 'Hasil audit kinerja triwulan III tahun 2022 dengan rekomendasi perbaikan untuk triwulan IV.',
                'pengirim' => 'Badan Pemeriksa Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Audit triwulan III 2022',
            ],
            [
                'nomor_surat' => 'SM/054/IX/2022',
                'tanggal_surat' => Carbon::create(2022, 9, 5),
                'tanggal_terima' => Carbon::create(2022, 9, 6),
                'perihal' => 'Implementasi Sistem Akuntansi Berbasis Akrual',
                'ringkasan_isi' => 'Implementasi sistem akuntansi berbasis akrual untuk meningkatkan transparansi dan akuntabilitas keuangan.',
                'pengirim' => 'Kementerian Keuangan',
                'sifat_surat' => 'Penting',
                'keterangan' => 'Sistem akuntansi akrual',
            ],
            [
                'nomor_surat' => 'SM/055/VIII/2022',
                'tanggal_surat' => Carbon::create(2022, 8, 15),
                'tanggal_terima' => Carbon::create(2022, 8, 16),
                'perihal' => 'Koordinasi Program Reformasi Birokrasi',
                'ringkasan_isi' => 'Koordinasi program reformasi birokrasi untuk meningkatkan kualitas pelayanan publik.',
                'pengirim' => 'Kementerian PANRB',
                'sifat_surat' => 'Segera',
                'keterangan' => 'Reformasi birokrasi',
            ],
        ];

        foreach ($sampleData as $data) {
            // Random bagian dan user
            $randomBagian = $bagian->random();
            $randomUser = $users->random();

            SuratMasuk::create([
                'nomor_surat' => $data['nomor_surat'],
                'tanggal_surat' => $data['tanggal_surat'],
                'tanggal_terima' => $data['tanggal_terima'],
                'perihal' => $data['perihal'],
                'ringkasan_isi' => $data['ringkasan_isi'],
                'pengirim' => $data['pengirim'],
                'sifat_surat' => $data['sifat_surat'],
                'keterangan' => $data['keterangan'],
                'tujuan_bagian_id' => $randomBagian->id,
                'user_id' => $randomUser->id,
                'created_by' => $randomUser->id,
                'updated_by' => $randomUser->id,
            ]);
        }

        $this->command->info('SuratMasukSeeder completed successfully!');
    }
}
